services:
  frontend:
    image: myblog-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:5203/api/v1
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge